# Generated by Django 6.0.3 on 2026-05-19 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('c_code_genre', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Cコード内容')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ジャンル名')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='書籍ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBNコード')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社名')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版日')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='表紙URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('genre', models.ForeignKey(blank=True, db_column='c_code_genre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.genre', verbose_name='Cコード内容')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='蔵書ID')),
                ('status', models.CharField(choices=[('available', '利用可能'), ('on_loan', '貸出中'), ('reserved', '予約中'), ('lost', '紛失')], default='available', max_length=20, verbose_name='ステータス')),
                ('location', models.CharField(max_length=255, verbose_name='保管場所')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購入日')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bookcopies', to='books.book', verbose_name='書籍ID')),
            ],
            options={
                'db_table': 'book_copy',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['available', 'on_loan', 'reserved', 'lost'])), name='book_copy_status_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='book_price_gte_0_or_null'),
        ),
    ]
