# Generated by Django 6.0.3 on 2026-05-19 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='貸出ID')),
                ('borrowed_date', models.DateField(verbose_name='貸出日')),
                ('due_date', models.DateField(verbose_name='返却期限日')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='実返却日')),
                ('extension_count', models.SmallIntegerField(default=0, verbose_name='延長回数')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lending', to='books.bookcopy', verbose_name='蔵書ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lending', to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
            options={
                'db_table': 'lending',
                'constraints': [models.UniqueConstraint(fields=('book_copy', 'user'), name='lending_book_copy_user_unique'), models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('borrowed_date'))), name='lending_due_date_gte_borrowed_date'), models.CheckConstraint(condition=models.Q(('returned_date__isnull', True), ('returned_date__gte', models.F('borrowed_date')), _connector='OR'), name='lending_returned_date_gte_borrowed_date'), models.CheckConstraint(condition=models.Q(('extension_count__gte', 0), ('extension_count__lte', 3)), name='lending_extension_count_between_0_3')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='予約ID')),
                ('scheduled_date', models.DateField(verbose_name='予定貸出日')),
                ('expires_date', models.DateField(verbose_name='取り置き期限')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.bookcopy', verbose_name='蔵書ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
            options={
                'db_table': 'reservation',
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_date__gte', models.F('scheduled_date'))), name='reservation_expires_date_gte_scheduled_date')],
            },
        ),
    ]
