# Generated by Django 6.0.3 on 2026-06-23 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_seed_genres'),
        ('lending', '0002_reservation_reservation_book_copy_user_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lending',
            name='lending_book_copy_user_unique',
        ),
        migrations.AddConstraint(
            model_name='lending',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_date__isnull', True)), fields=('book_copy',), name='lending_active_book_copy_unique'),
        ),
    ]
