# Generated by Django 6.0.3 on 2026-06-26 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_seed_genres'),
        ('lending', '0003_active_lending_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_book_copy_user_unique',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('book_copy',), name='reservation_book_copy_unique'),
        ),
    ]
